<?php

namespace NF_FU_VENDOR;

// autoload_psr4.php @generated by Composer
$vendorDir = \dirname(\dirname(__FILE__));
$baseDir = \dirname($vendorDir);
return array('phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'), 'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'), 'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'), 'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'), 'Polevaultweb\\WPOAuth2\\' => array($vendorDir . '/polevaultweb/wp-oauth2/src'), 'Polevaultweb\\WPDropboxAPI\\' => array($vendorDir . '/polevaultweb/wp-dropbox-api/src'), 'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'), 'JmesPath\\' => array($vendorDir . '/mtdowling/jmespath.php/src'), 'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'), 'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'), 'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'), 'Google\\Auth\\' => array($vendorDir . '/google/auth/src'), 'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'), 'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'), 'Aws\\' => array($vendorDir . '/aws/aws-sdk-php/src'));
