<?php

namespace NF_FU_VENDOR;

// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \NF_FU_VENDOR\ComposerAutoloaderInite2cf1719c8eecfb9c5da833295566ddb::getLoader();
