<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php';

// Functions whitelisting. For more information see:
// https://github.com/humbug/php-scoper/blob/master/README.md#functions-whitelisting
if (!function_exists('phpseclib_safe_serialize')) {
    function phpseclib_safe_serialize() {
        return \NF_FU_VENDOR\phpseclib_safe_serialize(...func_get_args());
    }
}
if (!function_exists('runSuite')) {
    function runSuite() {
        return \NF_FU_VENDOR\runSuite(...func_get_args());
    }
}
if (!function_exists('runCase')) {
    function runCase() {
        return \NF_FU_VENDOR\runCase(...func_get_args());
    }
}
if (!function_exists('uri_template')) {
    function uri_template() {
        return \NF_FU_VENDOR\uri_template(...func_get_args());
    }
}
if (!function_exists('oauth2client_php_autoload')) {
    function oauth2client_php_autoload() {
        return \NF_FU_VENDOR\oauth2client_php_autoload(...func_get_args());
    }
}
if (!function_exists('RuntimeException')) {
    function RuntimeException() {
        return \NF_FU_VENDOR\RuntimeException(...func_get_args());
    }
}
if (!function_exists('intVal')) {
    function intVal() {
        return \NF_FU_VENDOR\intVal(...func_get_args());
    }
}
if (!function_exists('composerRequiree2cf1719c8eecfb9c5da833295566ddb')) {
    function composerRequiree2cf1719c8eecfb9c5da833295566ddb() {
        return \NF_FU_VENDOR\composerRequiree2cf1719c8eecfb9c5da833295566ddb(...func_get_args());
    }
}
if (!function_exists('includeIfExists')) {
    function includeIfExists() {
        return \NF_FU_VENDOR\includeIfExists(...func_get_args());
    }
}
if (!function_exists('zend_monitor_custom_event')) {
    function zend_monitor_custom_event() {
        return \NF_FU_VENDOR\zend_monitor_custom_event(...func_get_args());
    }
}

return $loader;
